<<<<<<< HEAD

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
=======
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// 3 REDUX ASYNC ACTIONS
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
>>>>>>> 0518997423dc665571963fa1615e8c96f6852790
